extends:
  - 'eslint:recommended'
  - 'standard'
env:
  browser: true
  es6: true
  webextensions: true
parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  no-tabs:
    - error
    - allowIndentationTabs: true

overrides:
  - files:
      - "*.config.js"
    env:
      browser: false
      node: true
      es6: true
    parserOptions:
      sourceType: module
  - files:
      - "exe/*.js"
    env:
      browser: false
      node: true
